import ApiKeyGuide, { readSecurityFlags, saveSecurityFlags } from './components/ApiKeyGuide';
import { BookOpen } from 'lucide-react';
import CompetitionInsights from './components/CompetitionInsights';
import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, BarChart3, Check, ChevronDown, ChevronRight, Clock3, Database, Download, ExternalLink, FileJson, Filter, FolderHeart, HardDrive, Info, KeyRound, Layers2, LayoutDashboard, Menu, Plus, Radar, RefreshCw, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Star, Tag, Target, Trash2, TrendingUp, Upload, UsersRound, Video as VideoIcon, X, Youtube } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { db, addCompetitor, addOwner, exportBackup, importBackup, primaryOwner, purgeExpired, removeOwner, resetAll, saveChannelData } from './lib/storage';
import { getChannel, getChannelById, fetchRecentVideos, searchChannels, verifyApiKey } from './lib/youtube';
import { categories, dateLabel, durationLabel, kindOf, median, numberLabel, prettyNumber, sortByViews, timeLabel } from './lib/utils';
import type { Channel, Competitor, Owner, Page, SearchCandidate, Video } from './lib/types';

const REMEMBER_KEY='youtube-radar-key-v1';
function loadRememberedKey(){try{return window.localStorage.getItem(REMEMBER_KEY)||'';}catch{return '';}}
function persistKey(key:string){try{if(key)window.localStorage.setItem(REMEMBER_KEY,key);else window.localStorage.removeItem(REMEMBER_KEY);return true;}catch{return false;}}
type Tab = 'videos'|'categories';
const SIDEBAR_ITEMS: {id:Page;label:string;icon:typeof Search;group?:string}[]=[
 {id:'dashboard',label:'대시보드',icon:LayoutDashboard,group:'워크스페이스'},
 {id:'search',label:'채널 검색',icon:Search},
 {id:'library',label:'내 라이브러리',icon:FolderHeart},
 {id:'owners',label:'내 채널 관리',icon:UsersRound,group:'경쟁 분석'},
 {id:'discover',label:'경쟁 채널 탐색',icon:Radar},
 {id:'compare',label:'채널 성과 비교',icon:BarChart3},
 {id:'settings',label:'설정 및 데이터',icon:Settings2,group:'시스템'},
 {id:'api-guide',label:'API 키 발급 가이드',icon:BookOpen}];
const PAGE_INFO:Record<Page,{title:string;desc:string}>={dashboard:{title:'대시보드',desc:'저장한 채널을 한눈에 살펴보세요.'},search:{title:'채널 검색',desc:'궁금한 유튜브 채널을 검색하고 분석하세요.'},channel:{title:'채널 상세 분석',desc:'영상 성과와 채널 카테고리를 살펴보세요.'},owners:{title:'내 채널 관리',desc:'분석 기준으로 사용할 내 채널을 관리합니다.'},discover:{title:'경쟁 채널 탐색',desc:'같은 분야의 경쟁 채널을 찾고 저장하세요.'},compare:{title:'경쟁 성과 비교',desc:'기준 채널과 경쟁 채널을 나란히 비교합니다.'},library:{title:'내 라이브러리',desc:'이 브라우저에 저장된 채널과 수집 데이터를 관리합니다.'},settings:{title:'설정 및 데이터',desc:'API 키, 저장소, JSON 백업을 관리합니다.'},'api-guide':{title:'API 키 발급 가이드',desc:'Google Cloud가 처음이어도 괜찮습니다. 7단계로 안내합니다.'}};

function Stat({label,value,icon:Icon,sub}:{label:string;value:string;icon:typeof Search;sub?:string}) {return <div className="stat-card"><div className="stat-top"><span>{label}</span><span className="stat-symbol"><Icon size={18}/></span></div><div className="stat-number">{value}</div>{sub&&<div className="stat-foot">{sub}</div>}</div>}
function Empty({icon:Icon=Database,title,desc,button}:{icon?:typeof Search;title:string;desc:string;button?:ReactNode}){return <div className="empty"><div className="empty-icon"><Icon size={24}/></div><b>{title}</b><p>{desc}</p>{button}</div>}
function Pill({children,color='neutral'}:{children:ReactNode;color?:'neutral'|'green'|'amber'|'indigo'}){return <span className={`pill ${color}`}>{children}</span>}
function Avatar({channel,large=false}:{channel:Channel;large?:boolean}){return channel.thumbnail?<img className={`avatar ${large?'large':''}`} src={channel.thumbnail} alt="채널 프로필" referrerPolicy="no-referrer"/>:<span className={`avatar avatar-fallback ${large?'large':''}`}><Youtube size={large?24:18}/></span>}
function KindBadge({video}:{video:Video}){const type=kindOf(video);return <Pill color={type==='long'?'indigo':type==='short'?'green':'amber'}>{type==='long'?'롱폼':type==='short'?'쇼츠':'미분류'}</Pill>}
function DataNotice({children}:{children:ReactNode}){return <div className="notice"><Info size={17}/><span>{children}</span></div>}
function Select({value,onChange,children,ariaLabel}:{value:string;onChange:(v:string)=>void;children:ReactNode;ariaLabel:string}) {return <select aria-label={ariaLabel} value={value} onChange={e=>onChange(e.target.value)}>{children}</select>}
function VideoRow({video,onChange}:{video:Video;onChange:(kind:'long'|'short'|'unknown')=>Promise<void>}){const [editing,setEditing]=useState(false);return <div className="video-row"><a className="thumb" href={`https://www.youtube.com/watch?v=${video.id}`} target="_blank" rel="noreferrer"><img src={video.thumbnail} alt="영상 썸네일" loading="lazy" referrerPolicy="no-referrer"/><span className="duration">{durationLabel(video.durationSeconds)}</span></a><div className="video-main"><a className="video-title" href={`https://www.youtube.com/watch?v=${video.id}`} target="_blank" rel="noreferrer">{video.title}<ExternalLink size={12}/></a><div className="video-meta">{dateLabel(video.publishedAt)} <span>·</span> {categories[video.categoryId]??'기타'} <span>·</span> 좋아요 {numberLabel(video.likeCount)}</div><div className="video-kind"><KindBadge video={video}/><button className="link-button" onClick={()=>setEditing(s=>!s)}>{editing?'닫기':'유형 지정'}</button>{editing&&<select value={video.kindOverride??'unknown'} aria-label="영상 유형 직접 지정" onChange={e=>{void onChange(e.target.value as 'long'|'short'|'unknown');setEditing(false)}}><option value="unknown">자동/미분류</option><option value="long">롱폼</option><option value="short">쇼츠</option></select>}</div></div><div className="video-views"><b>{prettyNumber(video.viewCount)}</b><span>조회수</span></div></div>}

export default function App(){
 const initial=(()=>{const p=window.location.pathname.split('/').filter(Boolean);return (SIDEBAR_ITEMS.some(x=>x.id===p[0])?p[0]:(p[0]==='channel'?'channel':'dashboard')) as Page})();
 const [page,setPage]=useState<Page>(initial);const [channelId,setChannelId]=useState(()=>window.location.pathname.split('/')[2]||'');const [channels,setChannels]=useState<Channel[]>([]);const [videos,setVideos]=useState<Video[]>([]);const [owners,setOwners]=useState<Owner[]>([]);const [competitors,setCompetitors]=useState<Competitor[]>([]);
 const [apiKey,setApiKey]=useState(loadRememberedKey);const [remember,setRemember]=useState(()=>!!loadRememberedKey());const [busy,setBusy]=useState(false);const [status,setStatus]=useState('');const [toast,setToast]=useState('');const [mobileOpen,setMobileOpen]=useState(false);
 const refresh=useCallback(async()=>{await purgeExpired();const [chs,vs,os,cs]=await Promise.all([db.channels.toArray(),db.videos.toArray(),db.owners.toArray(),db.competitors.toArray()]);setChannels(chs.sort((a,b)=>b.fetchedAt.localeCompare(a.fetchedAt)));setVideos(vs);setOwners(os);setCompetitors(cs);},[]);
 useEffect(()=>{void refresh().catch(()=>notify('로컬 데이터베이스를 열 수 없습니다. 브라우저 설정을 확인해 주세요.'));},[refresh]);
 useEffect(()=>{const change=()=>{const parts=location.pathname.split('/').filter(Boolean);setPage((SIDEBAR_ITEMS.some(x=>x.id===parts[0])?parts[0]:(parts[0]==='channel'?'channel':'dashboard')) as Page);setChannelId(parts[1]||'');};window.addEventListener('popstate',change);return ()=>window.removeEventListener('popstate',change)},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return ()=>clearTimeout(t);},[toast]);
 function notify(text:string){setToast(text);}
 function navigate(next:Page,id?:string){const path=next==='dashboard'?'/':next==='channel'?`/channel/${id||channelId}`:`/${next}`;history.pushState({},'',path);setPage(next);if(id)setChannelId(id);setMobileOpen(false);window.scrollTo({top:0,behavior:'instant'});}
 function setKey(key:string,save:boolean){setApiKey(key);setRemember(save);if(!persistKey(save?key:''))notify('브라우저 설정으로 API 키 저장이 차단됐습니다. 이번 세션에만 사용합니다.');}
 const run=async(task:()=>Promise<void>)=>{if(busy)return;setBusy(true);setStatus('데이터 불러오는 중…');try {await task();await refresh();}catch(e){notify(e instanceof Error?e.message:'작업 중 오류가 발생했습니다.')}finally{setBusy(false);setStatus('');}};
 async function loadChannel(input:string,limit=50){if(!apiKey){navigate('settings');notify('먼저 API 키를 연결해 주세요.');return;}await run(async()=>{const channel=await getChannel(apiKey,input);setStatus(`${channel.title} 영상 수집 중…`);const list=await fetchRecentVideos(apiKey,channel,limit);await saveChannelData(channel,list);notify(`${channel.title}: 영상 ${list.length}개를 저장했습니다.`);navigate('channel',channel.id);});}
 async function refreshChannel(id:string,limit=50){if(!apiKey){navigate('settings');notify('갱신하려면 API 키를 연결해 주세요.');return;}await run(async()=>{const c=await getChannelById(apiKey,id);setStatus(`${c.title} 최신 영상 수집 중…`);const list=await fetchRecentVideos(apiKey,c,limit);await saveChannelData(c,list);notify(`${c.title}: 영상 ${list.length}개를 갱신했습니다.`);});}
 async function ensureChannel(id:string){const cached=channels.find(c=>c.id===id);if(cached)return cached;if(!apiKey)throw new Error('API 키를 연결해 주세요.');const c=await getChannelById(apiKey,id);const vs=await fetchRecentVideos(apiKey,c,50);await saveChannelData(c,vs);return c;}
 const activeChannel=channels.find(c=>c.id===channelId);
 const baseOwner=owners.find(o=>o.isPrimary)||owners[0];const baseChannel=channels.find(c=>c.id===baseOwner?.channelId);
 const allOwnerIds=new Set(owners.map(x=>x.channelId));
 const myCompIds=new Set(competitors.filter(c=>c.ownerId===baseOwner?.channelId).map(c=>c.channelId));
 const savedCounts={channels:channels.length,videos:videos.length,owners:owners.length};
 return <div className="shell">
 <aside className={`sidebar ${mobileOpen?'opened':''}`}>
  <div className="brand" onClick={()=>navigate('dashboard')} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==='Enter')navigate('dashboard')}}><span className="brand-logo"><Radar size={23}/></span><span className="brand-name">YouTube<span>Radar</span><small>CREATOR INTELLIGENCE</small></span></div>
  <div className="sidebar-scroll"><div className="side-nav">{SIDEBAR_ITEMS.map(item=>{const Icon=item.icon;return <div key={item.id}>{item.group&&<div className="nav-group">{item.group}</div>}<button className={`nav-item ${page===item.id?'active':''}`} onClick={()=>navigate(item.id)}><Icon size={18}/><span>{item.label}</span>{page===item.id&&<span className="nav-active-dot"/>}</button></div>})}</div>
  <div className="side-bottom"><div className="key-widget"><div className="key-widget-icon"><KeyRound size={17}/></div><div><b>{apiKey?'API 키 연결됨':'API 키 미연결'}</b><span>{apiKey?'내 브라우저에서 직접 요청':'연결 후 채널 분석 가능'}</span></div><button aria-label="API 키 설정" onClick={()=>navigate('settings')}><ChevronRight size={16}/></button></div><div className="sidebar-caption"><span className="online-dot"/> 로컬 전용 워크스페이스 <span className="version">v1.1.2</span></div></div></div>
 </aside>
 {mobileOpen&&<div className="sidebar-overlay" onClick={()=>setMobileOpen(false)}/>}
 <main className="main"><header className="topbar"><div className="top-left"><button aria-label="메뉴 열기" className="mobile-menu" onClick={()=>setMobileOpen(!mobileOpen)}><Menu size={21}/></button><span className="breadcrumb">워크스페이스</span><ChevronRight size={14}/><strong>{PAGE_INFO[page].title}</strong></div><div className="top-right"><span className="private-label"><ShieldCheck size={15}/> 개인 브라우저 저장</span><button className="top-icon-button" aria-label="설정" onClick={()=>navigate('settings')}><Settings2 size={18}/></button><div className="profile-circle">YR</div></div></header>
 <div className="content"><div className="page-head"><div><div className="eyebrow">YOUTUBE ANALYTICS WORKSPACE</div><h1>{PAGE_INFO[page].title}</h1><p>{PAGE_INFO[page].desc}</p></div><div className="page-tools"><span className="local-pill" aria-label="분석 결과는 현재 브라우저에 저장됩니다"><span className="local-dot"/> 브라우저에 저장됨</span>{apiKey && page!=='settings' && page!=='api-guide' && <button className="btn btn-secondary" onClick={()=>navigate('settings')}><KeyRound size={16}/> API 설정</button>}</div></div>
 {!apiKey && page!=='settings' && page!=='api-guide' && <div className="key-banner"><div><BookOpen size={18}/><span><b>처음 사용하시나요? API 키 만드는 방법부터 안내해 드립니다.</b> 이미 API 키가 있다면 바로 연결할 수 있습니다.</span></div><div className="yrg-banner-actions"><button className="yrg-onboarding-primary" onClick={()=>navigate('api-guide')}>API 키 발급 가이드 <ArrowRight size={15}/></button><button className="yrg-onboarding-secondary" onClick={()=>navigate('settings')}>이미 키가 있어요 <KeyRound size={15}/></button></div></div>}
 {page==='dashboard'&&<Dashboard channels={channels} videos={videos} owners={owners} base={baseChannel} nav={navigate} onRefresh={id=>void refreshChannel(id)} busy={busy} stats={savedCounts}/>}
 {page==='search'&&<SearchPage apiKey={apiKey} onLoad={loadChannel} nav={navigate} busy={busy} notify={notify}/>}
 {page==='channel'&&<ChannelPage channel={activeChannel} videos={videos.filter(v=>v.channelId===channelId)} owner={allOwnerIds.has(channelId)} comp={myCompIds.has(channelId)} onRefresh={limit=>void refreshChannel(channelId,limit)} onOwner={()=>void run(async()=>{await addOwner(channelId);notify('기준 채널로 등록했습니다.')})} onComp={()=>void run(async()=>{if(!baseOwner)throw new Error('먼저 내 채널을 등록해 주세요.');await addCompetitor(baseOwner.channelId,channelId);notify('경쟁 채널로 등록했습니다.')})} busy={busy} nav={navigate} update={refresh} notify={notify}/>}
 {page==='owners'&&<OwnersPage channels={channels} owners={owners} nav={navigate} update={refresh} notify={notify}/>}
 {page==='discover'&&<DiscoverPage apiKey={apiKey} channels={channels} base={baseChannel} baseOwner={baseOwner} competitorIds={myCompIds} videos={videos} nav={navigate} run={run} load={ensureChannel} notify={notify} busy={busy}/>}
 {page==='compare'&&<ComparePage channels={channels} owners={owners} competitors={competitors} videos={videos} nav={navigate}/>}
 {page==='library'&&<LibraryPage channels={channels} owners={owners} competitors={competitors} videos={videos} busy={busy} nav={navigate} refreshOne={id=>void refreshChannel(id)} update={refresh} notify={notify}/>}
 {page==='api-guide'&&<ApiKeyGuide onSettings={()=>navigate('settings')}/>}
 {page==='settings'&&<SettingsPage onGuide={()=>navigate('api-guide')} apiKey={apiKey} remember={remember} setKey={setKey} notify={notify} refresh={refresh} busy={busy} run={run} stats={savedCounts}/>}
 <footer className="footer"><span>© 2026 YouTube Radar · 브라우저 로컬 분석</span><span>YouTube 공식 서비스가 아닙니다. · <a href="https://developers.google.com/youtube/v3" target="_blank" rel="noreferrer">YouTube Data API</a></span></footer></div></main>
 {busy&&<div className="busy-overlay" role="status"><div className="busy-indicator"><RefreshCw className="spin" size={22}/><div><b>데이터 처리 중</b><small>{status}</small></div></div></div>}
 {toast&&<div role="status" className="toast"><Info size={17}/>{toast}<button onClick={()=>setToast('')} aria-label="닫기"><X size={16}/></button></div>}
 </div>
}

function Dashboard({channels,videos,owners,base,nav,onRefresh,busy,stats}:{channels:Channel[];videos:Video[];owners:Owner[];base?:Channel;nav:(p:Page,id?:string)=>void;onRefresh:(id:string)=>void;busy:boolean;stats:{channels:number;videos:number;owners:number}}){const latest=sortByViews(videos).slice(0,4);const categoriesByCount=videos.reduce<Record<string,number>>((a,v)=>(a[v.categoryId]=(a[v.categoryId]||0)+1,a),{});const cat=Object.entries(categoriesByCount).sort((a,b)=>b[1]-a[1])[0];return <>
 <section className="hero"><div className="hero-content"><div className="hero-kicker"><Sparkles size={14}/> 크리에이터를 위한 인사이트</div><h2>더 나은 콘텐츠의 시작,<br/><span>데이터에서 답을 찾으세요.</span></h2><p>경쟁 채널을 분석하고, 인기 영상을 발견하고,<br/>다음 콘텐츠의 방향을 찾아보세요.</p><div className="hero-actions"><button className="btn btn-white" onClick={()=>nav('search')}>채널 분석 시작하기 <ArrowRight size={17}/></button><button className="btn btn-ghost" onClick={()=>nav('discover')}>경쟁 채널 탐색 <ArrowUpRight size={16}/></button></div></div><div className="hero-graphic" aria-hidden="true"><div className="orbit outer"/><div className="orbit middle"/><div className="orbit inner"/><div className="radar-mark"><Radar size={64}/></div><span className="radar-point p1"/><span className="radar-point p2"/><span className="radar-point p3"/><span className="radar-point p4"/></div></section>
 <div className="section-title"><div><h2>워크스페이스 현황</h2><p>이 브라우저에 저장된 분석 데이터를 요약합니다.</p></div><span className="updated-label"><Clock3 size={14}/> 로컬 기준</span></div>
 <div className="stats-grid"><Stat label="저장된 채널" value={`${stats.channels}`} icon={Layers2} sub="분석한 전체 채널"/><Stat label="수집한 영상" value={`${stats.videos}`} icon={VideoIcon} sub="공개 영상 데이터"/><Stat label="내 기준 채널" value={`${stats.owners}`} icon={UsersRound} sub="경쟁 비교 기준"/><Stat label="주요 카테고리" value={cat?categories[cat[0]]||'기타':'—'} icon={Tag} sub={cat?`${cat[1]}개 영상`: '수집 데이터 없음'}/></div>
 <div className="dashboard-grid"><div className="panel"><div className="panel-head"><div><h3>최근 분석한 채널</h3><p>최근 수집한 채널을 빠르게 열어보세요.</p></div><button className="text-action" onClick={()=>nav('library')}>모두 보기 <ArrowRight size={15}/></button></div>{channels.length?channels.slice(0,4).map(c=><div className="channel-list-row" key={c.id}><button className="channel-list-name" onClick={()=>nav('channel',c.id)}><Avatar channel={c}/><span><b>{c.title}</b><small>구독자 {prettyNumber(c.subscriberCount)} · {timeLabel(c.fetchedAt)} 수집</small></span></button><div className="channel-row-actions">{owners.some(o=>o.channelId===c.id)&&<Pill color="indigo">내 채널</Pill>}<button title="지금 갱신" className="icon-soft" disabled={busy} onClick={()=>onRefresh(c.id)}><RefreshCw size={16}/></button><button title="채널 상세" className="icon-soft" onClick={()=>nav('channel',c.id)}><ChevronRight size={17}/></button></div></div>):<Empty icon={Search} title="아직 분석한 채널이 없습니다" desc="채널을 검색해 첫 데이터를 저장해 보세요." button={<button className="btn btn-primary" onClick={()=>nav('search')}>채널 검색하기 <ArrowRight size={15}/></button>}/>}</div>
 <div className="panel insight-panel"><div className="panel-head"><div><h3>내 채널 경쟁 분석</h3><p>기준 채널을 선택해 분석을 시작하세요.</p></div><Target size={19} className="muted-icon"/></div>{base?<><div className="base-profile"><Avatar channel={base} large/><div><span className="label-mini">현재 기준 채널</span><b>{base.title}</b><small>구독자 {prettyNumber(base.subscriberCount)}</small></div><Pill color="green">대표</Pill></div><div className="base-details"><span>최근 분석 영상</span><b>{videos.filter(v=>v.channelId===base.id).length}개</b></div><div className="base-details"><span>채널 주제</span><b>{base.topics[0]||'추가 분석 필요'}</b></div><button className="btn btn-primary full" onClick={()=>nav('compare')}>경쟁 성과 비교 <ArrowRight size={17}/></button></>:<Empty icon={UsersRound} title="내 기준 채널을 등록해 주세요" desc="저장한 채널을 기준으로 경쟁 채널을 분석할 수 있습니다." button={<button className="btn btn-primary" onClick={()=>nav('owners')}>내 채널 관리 <ArrowRight size={15}/></button>}/>}</div></div>
 <div className="panel dashboard-videos"><div className="panel-head"><div><h3>저장된 영상 중 조회수 TOP</h3><p>현재 저장된 영상의 누적 조회수 기준입니다. 실시간 전체 인기 순위가 아닙니다.</p></div><TrendingUp size={19} className="muted-icon"/></div>{latest.length?<div className="top-video-grid">{latest.map((v,i)=><div key={v.id} className="top-video-card"><a href={`https://youtube.com/watch?v=${v.id}`} target="_blank" rel="noreferrer" className="top-video-thumb"><img src={v.thumbnail} alt="영상 썸네일" loading="lazy"/><span>#{i+1}</span></a><div className="top-video-body"><a href={`https://youtube.com/watch?v=${v.id}`} target="_blank" rel="noreferrer" className="top-video-name">{v.title}</a><div><b>{prettyNumber(v.viewCount)}</b> <small>조회수</small></div></div></div>)}</div>:<Empty icon={TrendingUp} title="분석한 영상이 없습니다" desc="채널 분석을 진행하면 조회수 상위 영상을 여기에서 확인할 수 있습니다."/>}</div>
 </>}

function SearchPage({apiKey,onLoad,nav,busy,notify}:{apiKey:string;onLoad:(q:string)=>Promise<void>;nav:(p:Page,id?:string)=>void;busy:boolean;notify:(s:string)=>void}){const [query,setQuery]=useState('');const [results,setResults]=useState<SearchCandidate[]>([]);const [searching,setSearching]=useState(false);const [tried,setTried]=useState(false);async function submit(e?:FormEvent){e?.preventDefault();if(!query.trim())return;if(!apiKey){notify('설정에서 API 키를 입력해 주세요.');nav('settings');return;}const direct=/youtube\.com\/(@|channel\/)|^@|^UC[\w-]{20,}$/.test(query.trim());if(direct){await onLoad(query.trim());return;}setSearching(true);setTried(true);try{setResults(await searchChannels(apiKey,query));}catch(e){notify(e instanceof Error?e.message:'검색에 실패했습니다.');}finally{setSearching(false);}}
 return <><div className="search-hero panel"><span className="mini-overline"><Search size={14}/> CHANNEL DISCOVERY</span><h2>분석할 유튜브 채널을 찾아보세요</h2><p>채널 URL, @핸들, 채널명으로 검색할 수 있습니다. 한국어 관련 결과를 우선 표시합니다.</p><form className="large-search" onSubmit={submit}><Search size={21}/><input aria-label="채널 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="채널명 또는 youtube.com/@채널핸들"/><button className="btn btn-primary" disabled={busy||searching||!query.trim()}>{searching?'검색 중…':'채널 찾기'} <ArrowRight size={17}/></button></form><div className="search-examples"><span>검색 예시</span>{['@GoogleDevelopers','요리 채널','게임 리뷰'].map(x=><button key={x} onClick={()=>setQuery(x)}>{x} <ArrowUpRight size={12}/></button>)}</div></div>
 {tried&&<div className="panel search-results"><div className="panel-head"><div><h3>채널 검색 결과</h3><p>{results.length}개 후보 · 채널 선택 시 최근 영상 50개를 수집합니다.</p></div></div>{searching?<div className="skeleton-area">검색 결과를 불러오는 중…</div>:results.length?results.map(c=><div className="candidate" key={c.id}><span className="avatar avatar-fallback">{c.thumbnail?<img src={c.thumbnail} alt="채널 이미지"/>:<Youtube size={19}/>}</span><div className="candidate-detail"><b>{c.title}</b><small>{c.description||'채널 설명 없음'}</small></div><button disabled={busy} className="btn btn-outline" onClick={()=>void onLoad(c.id)}>분석하기 <ArrowRight size={15}/></button></div>):<Empty icon={Search} title="검색 결과가 없습니다" desc="다른 키워드나 정확한 채널 URL로 검색해 보세요."/>}</div>}
 <div className="feature-tip"><ShieldCheck size={18}/><span><b>개인정보 보호 우선</b> 검색 및 분석 결과는 외부 데이터베이스가 아닌 현재 브라우저의 IndexedDB에 저장됩니다.</span></div></>}

function ChannelPage({channel,videos,owner,comp,onRefresh,onOwner,onComp,busy,nav,update,notify}:{channel?:Channel;videos:Video[];owner:boolean;comp:boolean;onRefresh:(limit:number)=>void;onOwner:()=>void;onComp:()=>void;busy:boolean;nav:(p:Page,id?:string)=>void;update:()=>Promise<void>;notify:(s:string)=>void}){const [tab,setTab]=useState<Tab>('videos');const [kind,setKind]=useState('all');const [order,setOrder]=useState('recent');const [filter,setFilter]=useState('');const [limit,setLimit]=useState('50');const [period,setPeriod]=useState('all');const [more,setMore]=useState(false);
 const shown=useMemo(()=>videos.filter(v=>{if(kind!=='all'&&kindOf(v)!==kind)return false;if(!v.title.toLowerCase().includes(filter.toLowerCase()))return false;if(period!=='all'&&Date.now()-Date.parse(v.publishedAt)>Number(period)*86400000)return false;return true;}).sort((a,b)=>order==='views'?(b.viewCount??-1)-(a.viewCount??-1):order==='likes'?(b.likeCount??-1)-(a.likeCount??-1):order==='oldest'?a.publishedAt.localeCompare(b.publishedAt):b.publishedAt.localeCompare(a.publishedAt)),[videos,kind,filter,order,period]);
 const counts=videos.reduce<Record<string,number>>((a,v)=>(a[v.categoryId]=(a[v.categoryId]||0)+1,a),{});const maxCount=Math.max(1,...Object.values(counts));const sorted=Object.entries(counts).sort((a,b)=>b[1]-a[1]);const medianViews=median(videos.map(v=>v.viewCount).filter((x):x is number=>x!==null));
 if(!channel)return <div className="panel"><Empty icon={Search} title="저장된 채널을 찾을 수 없습니다" desc="이 브라우저에 저장되지 않았거나 유효 기간이 지난 채널입니다." button={<button className="btn btn-primary" onClick={()=>nav('search')}>채널 검색 <ArrowRight size={15}/></button>}/></div>;
 return <><button className="back-link" onClick={()=>nav('library')}><ArrowLeft size={16}/> 내 라이브러리</button><div className="panel channel-intro"><div className="channel-intro-top"><Avatar channel={channel} large/><div className="channel-identity"><div className="channel-label"><Pill color="indigo">YouTube 채널</Pill>{owner&&<Pill color="green">내 기준 채널</Pill>}{comp&&<Pill>경쟁 채널</Pill>}</div><h2>{channel.title}</h2><p>{channel.handle||channel.country||'공개 채널'} · 마지막 갱신 {timeLabel(channel.fetchedAt)}</p></div><div className="channel-intro-actions"><button className="btn btn-outline" onClick={onOwner} disabled={owner||busy}><Star size={16}/>{owner?'내 채널 등록됨':'내 채널 등록'}</button><button className="btn btn-outline" onClick={onComp} disabled={comp||busy}><Plus size={16}/>{comp?'경쟁 채널 등록됨':'경쟁 채널 등록'}</button><button className="btn btn-primary" disabled={busy} onClick={()=>onRefresh(Number(limit))}><RefreshCw size={16}/> 수동 갱신</button></div></div><div className="channel-stats"><div><small>구독자 수</small><strong>{prettyNumber(channel.subscriberCount)}</strong></div><div><small>채널 누적 조회수</small><strong>{prettyNumber(channel.viewCount)}</strong></div><div><small>전체 공개 영상</small><strong>{prettyNumber(channel.videoCount)}</strong></div><div><small>수집 영상 중앙값</small><strong>{prettyNumber(medianViews)}</strong></div></div><div className="refresh-options"><span><Info size={14}/> 조회수 증가는 두 번 이상 수동 갱신해야 확인할 수 있습니다.</span><button className="link-button" onClick={()=>setMore(!more)}>수집 범위 설정 <ChevronDown size={14}/></button>{more&&<Select value={limit} onChange={setLimit} ariaLabel="수집할 최근 영상 수"><option value="50">최근 50개</option><option value="100">최근 100개</option><option value="200">최근 200개</option></Select>}</div></div>
 <div className="tab-bar"><button className={tab==='videos'?'selected':''} onClick={()=>setTab('videos')}><VideoIcon size={17}/> 영상 분석 <span>{videos.length}</span></button><button className={tab==='categories'?'selected':''} onClick={()=>setTab('categories')}><Tag size={17}/> 카테고리 분석</button></div>
 {tab==='videos'?<div className="panel table-panel"><div className="panel-head"><div><h3>영상 성과 분석</h3><p>필터와 정렬은 브라우저의 저장 데이터만 사용합니다.</p></div><span className="updated-label">{shown.length}개 표시</span></div><div className="video-toolbar"><div className="filter-search"><Search size={17}/><input aria-label="저장 영상 제목 검색" placeholder="영상 제목 검색" value={filter} onChange={e=>setFilter(e.target.value)}/></div><Select value={kind} onChange={setKind} ariaLabel="영상 유형"><option value="all">전체 유형</option><option value="long">롱폼</option><option value="short">쇼츠(직접 지정)</option><option value="unknown">미분류</option></Select><Select value={period} onChange={setPeriod} ariaLabel="업로드 기간"><option value="all">전체 기간</option><option value="7">최근 7일</option><option value="30">최근 30일</option><option value="90">최근 90일</option></Select><Select value={order} onChange={setOrder} ariaLabel="정렬 기준"><option value="recent">최신 업로드순</option><option value="views">조회수 높은순</option><option value="likes">좋아요 높은순</option><option value="oldest">오래된순</option></Select></div><DataNotice>3분 이하 영상은 공식 쇼츠 판별값이 없어 기본적으로 미분류됩니다. 필요하면 '유형 지정'에서 직접 지정하세요.</DataNotice><div className="video-list">{shown.length?shown.map(v=><VideoRow key={v.id} video={v} onChange={async k=>{await db.videos.update(v.id,{kindOverride:k==='unknown'?undefined:k});await update();notify('영상 유형을 저장했습니다.')}}/>):<Empty icon={Filter} title="조건에 맞는 영상이 없습니다" desc="필터를 바꾸거나 영상을 수집해 주세요."/>}</div></div>:<div className="categories-grid"><div className="panel"><div className="panel-head"><div><h3>영상 카테고리 분포</h3><p>수집한 영상의 공식 categoryId 기준</p></div></div>{sorted.length?sorted.map(([id,n])=><div className="category-row" key={id}><div><b>{categories[id]||`카테고리 ${id}`}</b><small>{n}개 · {Math.round(n/videos.length*100)}%</small></div><div className="category-track"><div style={{width:`${n/maxCount*100}%`}}/></div></div>):<Empty icon={Tag} title="카테고리 데이터가 없습니다" desc="채널을 갱신하면 분석할 수 있습니다."/>}</div><div className="panel"><div className="panel-head"><div><h3>채널 주제 정보</h3><p>YouTube에서 제공한 공개 topicDetails</p></div></div>{channel.topics.length?<div className="topic-list">{channel.topics.map(x=><Pill key={x} color="indigo">{x}</Pill>)}</div>:<Empty icon={Tag} title="공식 채널 주제가 없습니다" desc="이 채널의 주제 메타데이터는 공개되지 않았습니다."/>}<DataNotice>주제 정보는 제공되지 않을 수 있으며, 영상 카테고리와 채널의 실제 세부 전문 분야는 서로 다를 수 있습니다.</DataNotice></div></div>}
 </>}

function OwnersPage({channels,owners,nav,update,notify}:{channels:Channel[];owners:Owner[];nav:(p:Page,id?:string)=>void;update:()=>Promise<void>;notify:(s:string)=>void}){const [selected,setSelected]=useState('');const candidates=channels.filter(c=>!owners.some(o=>o.channelId===c.id));return <><div className="panel"><div className="panel-head"><div><h3>내 채널 등록</h3><p>로그인이나 소유권 인증 없이 공개 채널을 비교 기준으로 지정합니다.</p></div><UsersRound className="muted-icon" size={20}/></div><div className="form-inline"><Select value={selected} onChange={setSelected} ariaLabel="기준 채널 선택"><option value="">저장된 채널 선택</option>{candidates.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</Select><button className="btn btn-primary" disabled={!selected} onClick={()=>void (async()=>{await addOwner(selected);setSelected('');await update();notify('내 채널로 등록했습니다.');})()}><Plus size={16}/> 채널 등록</button><button className="btn btn-outline" onClick={()=>nav('search')}><Search size={16}/> 새 채널 검색</button></div></div><div className="section-title section-tight"><div><h2>등록한 기준 채널</h2><p>대표 채널 하나를 기본값으로 사용하고 언제든 변경할 수 있습니다.</p></div><Pill>{owners.length}개 등록</Pill></div><div className="owner-grid">{owners.length?owners.map(o=>{const c=channels.find(x=>x.id===o.channelId);return <div className="panel owner-card" key={o.channelId}><div className="owner-card-head"><Pill color={o.isPrimary?'green':'neutral'}>{o.isPrimary?'대표 채널':'추가 채널'}</Pill><button className="icon-soft" aria-label="기준 채널 삭제" onClick={()=>{if(confirm('내 채널 목록에서 제거하시겠습니까? 저장된 공개 채널 데이터는 유지됩니다.')) void removeOwner(o.channelId).then(update)}}><Trash2 size={16}/></button></div><div className="owner-identity">{c?<Avatar channel={c} large/>:<span className="avatar avatar-fallback large"><UsersRound/></span>}<div><h3>{c?.title||'정보 갱신 필요'}</h3><p>구독자 {prettyNumber(c?.subscriberCount)}</p></div></div><div className="owner-card-actions"><button className="btn btn-outline" onClick={()=>nav('channel',o.channelId)}>분석 보기</button><button className="btn btn-primary" disabled={o.isPrimary} onClick={()=>void primaryOwner(o.channelId).then(update)}>{o.isPrimary?'대표 지정됨':'대표로 지정'}</button></div></div>}):<div className="panel owner-empty"><Empty icon={UsersRound} title="기준 채널이 없습니다" desc="먼저 채널을 검색한 뒤 내 채널로 등록해 주세요." button={<button className="btn btn-primary" onClick={()=>nav('search')}>채널 검색하기 <ArrowRight size={15}/></button>}/></div>}</div></>}

function DiscoverPage({apiKey,channels,base,baseOwner,competitorIds,videos,nav,run,load,notify,busy}:{apiKey:string;channels:Channel[];base?:Channel;baseOwner?:Owner;competitorIds:Set<string>;videos:Video[];nav:(p:Page,id?:string)=>void;run:(task:()=>Promise<void>)=>Promise<void>;load:(id:string)=>Promise<Channel>;notify:(t:string)=>void;busy:boolean}){const [query,setQuery]=useState('');const [found,setFound]=useState<SearchCandidate[]>([]);const [searched,setSearched]=useState(false);const [searchBusy,setSearchBusy]=useState(false);const ownerVideos=videos.filter(v=>v.channelId===base?.id);const topCategory=Object.entries(ownerVideos.reduce<Record<string,number>>((a,v)=>(a[v.categoryId]=(a[v.categoryId]||0)+1,a),{})).sort((a,b)=>b[1]-a[1])[0]?.[0];const suggestion=topCategory?categories[topCategory]:'';
 async function find(e?:FormEvent){e?.preventDefault();if(!apiKey){notify('먼저 API 키를 연결해 주세요.');nav('settings');return;}const q=query.trim()||suggestion;if(!q){notify('검색할 주제 키워드를 입력해 주세요.');return;}setSearchBusy(true);try{const res=await searchChannels(apiKey,q,10);setFound(res.filter(x=>x.id!==base?.id));setSearched(true);}catch(e){notify(e instanceof Error?e.message:'검색에 실패했습니다.');}finally{setSearchBusy(false);}}
 if(!baseOwner)return <div className="panel"><Empty icon={Target} title="먼저 내 기준 채널을 설정하세요" desc="경쟁 채널을 연결할 대표 채널이 필요합니다." button={<button className="btn btn-primary" onClick={()=>nav('owners')}>내 채널 관리 <ArrowRight size={16}/></button>}/></div>;
 return <><div className="panel discover-top"><div className="panel-head"><div><h3>기준 채널</h3><p>경쟁 후보 탐색에 사용할 대표 채널입니다.</p></div><button className="text-action" onClick={()=>nav('owners')}>기준 변경 <ArrowRight size={15}/></button></div><div className="base-inline">{base?<Avatar channel={base}/>:<span className="avatar avatar-fallback"><Youtube/></span>}<div><b>{base?.title||'채널 정보가 없습니다'}</b><span>대표 기준 채널 · 공개 콘텐츠 기반</span></div></div><form className="large-search" onSubmit={find}><Search size={20}/><input aria-label="경쟁 채널 주제 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder={suggestion?`예: ${suggestion}, 스마트폰 리뷰`:'분석할 주제 또는 키워드'}/><button className="btn btn-primary" disabled={busy||searchBusy}>{searchBusy?'탐색 중…':'경쟁 후보 찾기'} <ArrowRight size={16}/></button></form><DataNotice>후보는 키워드 검색 결과이며 실제 경쟁 관계를 확정하거나 추천 점수를 매기지 않습니다. 구독자 규모 제한 없이 직접 선택할 수 있습니다.</DataNotice></div>
 {searched&&<div className="panel search-results"><div className="panel-head"><div><h3>검색된 채널 후보</h3><p>{found.length}개 검색 결과 · 비교하고 싶은 채널을 저장하세요.</p></div></div>{found.length?found.map(c=><div className="candidate" key={c.id}><span className="avatar avatar-fallback">{c.thumbnail?<img src={c.thumbnail} alt="채널 이미지"/>:<Youtube size={19}/>}</span><div className="candidate-detail"><b>{c.title}</b><small>{c.description||'채널 설명 없음'}</small></div><button className="btn btn-outline" disabled={busy||competitorIds.has(c.id)} onClick={()=>void run(async()=>{await load(c.id);await addCompetitor(baseOwner.channelId,c.id);notify(`${c.title} 채널을 경쟁 목록에 추가했습니다.`);})}>{competitorIds.has(c.id)?<><Check size={15}/> 등록됨</>:<><Plus size={15}/> 경쟁 채널 추가</>}</button></div>):<Empty icon={Search} title="후보를 찾을 수 없습니다" desc="검색어를 더 구체적으로 입력해 보세요."/>}</div>}
 <div className="panel"><div className="panel-head"><div><h3>이미 저장된 채널 연결</h3><p>채널 데이터를 다시 수집하지 않고 경쟁 목록에 연결합니다.</p></div></div><div className="compact-grid">{channels.filter(c=>c.id!==baseOwner.channelId&&!competitorIds.has(c.id)).slice(0,12).map(c=><div className="compact-channel" key={c.id}><Avatar channel={c}/><b>{c.title}</b><button aria-label={`${c.title} 경쟁 채널로 추가`} onClick={()=>void run(async()=>{await addCompetitor(baseOwner.channelId,c.id);notify('경쟁 목록에 추가했습니다.');})}><Plus size={16}/></button></div>)}{!channels.some(c=>c.id!==baseOwner.channelId&&!competitorIds.has(c.id))&&<span className="muted">연결할 다른 저장 채널이 없습니다.</span>}</div></div>
 </>}

function ComparePage({channels,owners,competitors,videos,nav}:{channels:Channel[];owners:Owner[];competitors:Competitor[];videos:Video[];nav:(p:Page,id?:string)=>void}){const primary=owners.find(x=>x.isPrimary)||owners[0];const [ownerId,setOwnerId]=useState(primary?.channelId||'');const owner=ownerId||primary?.channelId||'';const compIds=competitors.filter(x=>x.ownerId===owner).map(x=>x.channelId);const [compId,setCompId]=useState('');const compareId=compIds.includes(compId)?compId:compIds[0];const [kind,setKind]=useState('all');const [period,setPeriod]=useState('all');const getVs=(id:string)=>videos.filter(v=>v.channelId===id&&(kind==='all'||kindOf(v)===kind)&&(period==='all'||Date.now()-Date.parse(v.publishedAt)<=Number(period)*86400000));const cv=owner?getVs(owner):[],vv=compareId?getVs(compareId):[];const a=channels.find(c=>c.id===owner);const b=channels.find(c=>c.id===compareId);const mean=(list:Video[])=>{const n=list.map(v=>v.viewCount).filter((x):x is number=>x!==null);return n.length?Math.round(n.reduce((s,x)=>s+x,0)/n.length):null;};const raw=[{name:a?.title||'기준 채널',views:mean(cv)??0},{name:b?.title||'경쟁 채널',views:mean(vv)??0}];
 return <><div className="panel"><div className="panel-head"><div><h3>비교 조건</h3><p>동일한 필터로 저장된 공개 영상 통계를 비교합니다.</p></div><SlidersHorizontal size={19} className="muted-icon"/></div><div className="compare-controls"><label>기준 채널<Select value={owner} onChange={setOwnerId} ariaLabel="비교 기준 채널"><option value="">기준 채널 선택</option>{owners.map(o=><option key={o.channelId} value={o.channelId}>{channels.find(c=>c.id===o.channelId)?.title||o.channelId}</option>)}</Select></label><label>경쟁 채널<Select value={compareId||''} onChange={setCompId} ariaLabel="비교할 경쟁 채널"><option value="">경쟁 채널 선택</option>{compIds.map(id=><option key={id} value={id}>{channels.find(c=>c.id===id)?.title||id}</option>)}</Select></label><label>영상 유형<Select value={kind} onChange={setKind} ariaLabel="영상 유형 비교"><option value="all">전체</option><option value="long">롱폼</option><option value="short">쇼츠(직접 지정)</option><option value="unknown">미분류</option></Select></label><label>업로드 기간<Select value={period} onChange={setPeriod} ariaLabel="기간 비교"><option value="all">전체 수집</option><option value="30">최근 30일</option><option value="90">최근 90일</option></Select></label></div></div>
 {!a||!b?<div className="panel"><Empty icon={BarChart3} title="비교할 채널이 필요합니다" desc="기준 채널을 등록하고 경쟁 채널을 한 개 이상 연결해 주세요." button={<button className="btn btn-primary" onClick={()=>nav('discover')}>경쟁 채널 찾기 <ArrowRight size={16}/></button>}/></div>:<><div className="compare-table panel"><div className="panel-head"><div><h3>채널 핵심 지표</h3><p>선택된 영상 표본을 기준으로 비교합니다.</p></div></div><div className="comparison-line comparison-header"><span>비교 항목</span><div><Avatar channel={a}/><b>{a.title}</b></div><div><Avatar channel={b}/><b>{b.title}</b></div></div>{[{label:'구독자',x:a.subscriberCount,y:b.subscriberCount},{label:'채널 누적 조회수',x:a.viewCount,y:b.viewCount},{label:'조건에 맞는 영상',x:cv.length,y:vv.length},{label:'영상 평균 조회수',x:mean(cv),y:mean(vv)},{label:'영상 조회수 중앙값',x:median(cv.map(v=>v.viewCount).filter((x):x is number=>x!==null)),y:median(vv.map(v=>v.viewCount).filter((x):x is number=>x!==null))}].map(item=><div className="comparison-line" key={item.label}><span>{item.label}</span><strong>{prettyNumber(item.x)}</strong><strong>{prettyNumber(item.y)}</strong></div>)}<div className="compare-freshness"><Clock3 size={15}/> 데이터 수집 시각: {a.title} {timeLabel(a.fetchedAt)} / {b.title} {timeLabel(b.fetchedAt)}</div></div><div className="panel"><div className="panel-head"><div><h3>영상 평균 조회수 비교</h3><p>저장된 영상 중 현재 필터에 맞는 표본의 산술 평균</p></div></div>{cv.length&&vv.length?<div className="chart-area"><ResponsiveContainer width="100%" height={258}><BarChart data={raw} layout="vertical" margin={{left:5,right:34,top:10,bottom:0}}><CartesianGrid stroke="#edf0f5" strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tickFormatter={prettyNumber} tick={{fill:'#8791a1',fontSize:12}} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="name" width={108} tick={{fill:'#5d6779',fontSize:11}} axisLine={false} tickLine={false}/><Tooltip formatter={v=>numberLabel(Number(v))}/><Bar dataKey="views" fill="#596de5" radius={[0,6,6,0]} barSize={34}/></BarChart></ResponsiveContainer></div>:<Empty icon={BarChart3} title="비교할 영상이 부족합니다" desc="영상 유형이나 기간 필터를 변경해 보세요."/>}</div><CompetitionInsights base={a} competitors={compIds.map(id=>channels.find(c=>c.id===id)).filter((c):c is Channel=>!!c)} videos={videos}/><DataNotice>조회수는 게시 이후 누적값입니다. 업로드 후 같은 시간이 지난 시점의 조회수는 관측 기록이 있는 경우에만 정확히 비교할 수 있습니다. 원본 통계만 제공하며 자체 성공 점수는 계산하지 않습니다.</DataNotice></>}
 </>}

function LibraryPage({channels,owners,competitors,videos,busy,nav,refreshOne,update,notify}:{channels:Channel[];owners:Owner[];competitors:Competitor[];videos:Video[];busy:boolean;nav:(p:Page,id?:string)=>void;refreshOne:(id:string)=>void;update:()=>Promise<void>;notify:(s:string)=>void}){const [filter,setFilter]=useState('');const shown=channels.filter(c=>c.title.toLowerCase().includes(filter.toLowerCase()));async function remove(id:string){if(!confirm('이 채널과 영상 데이터를 이 브라우저에서 삭제하시겠습니까? 기준 채널·경쟁 관계도 제거됩니다.'))return;await db.transaction('rw',db.channels,db.videos,db.snapshots,db.owners,db.competitors,async()=>{const ids=(await db.videos.where('channelId').equals(id).primaryKeys()) as string[];await db.channels.delete(id);await db.videos.where('channelId').equals(id).delete();if(ids.length)await db.snapshots.where('videoId').anyOf(ids).delete();const wasPrimary=(await db.owners.get(id))?.isPrimary;await db.owners.delete(id);if(wasPrimary){const next=(await db.owners.toArray()).sort((a,b)=>a.addedAt.localeCompare(b.addedAt))[0];if(next)await db.owners.update(next.channelId,{isPrimary:true});}await db.competitors.where('channelId').equals(id).delete();await db.competitors.where('ownerId').equals(id).delete();});await update();notify('채널 데이터를 삭제했습니다.');}
 return <div className="panel"><div className="panel-head"><div><h3>저장한 채널</h3><p>모든 분석 데이터는 이 브라우저에만 보관됩니다.</p></div><button className="btn btn-primary" onClick={()=>nav('search')}><Plus size={16}/> 채널 추가</button></div><div className="library-toolbar"><div className="filter-search"><Search size={17}/><input aria-label="저장 채널 검색" placeholder="저장된 채널 검색" value={filter} onChange={e=>setFilter(e.target.value)}/></div><Pill>{shown.length}개 채널</Pill></div>{shown.length?<div className="library-list">{shown.map(c=><div className="library-row" key={c.id}><button className="library-channel" onClick={()=>nav('channel',c.id)}><Avatar channel={c} large/><span><b>{c.title}</b><small>구독자 {prettyNumber(c.subscriberCount)} · 저장 영상 {videos.filter(v=>v.channelId===c.id).length}개</small><small>갱신 {timeLabel(c.fetchedAt)}</small></span></button><div className="library-actions">{owners.some(o=>o.channelId===c.id)&&<Pill color="indigo">내 채널</Pill>}{competitors.some(x=>x.channelId===c.id)&&<Pill>경쟁</Pill>}<button className="icon-soft" title="수동 갱신" disabled={busy} onClick={()=>refreshOne(c.id)}><RefreshCw size={17}/></button><button className="icon-soft" title="삭제" onClick={()=>void remove(c.id)}><Trash2 size={17}/></button><button className="icon-soft" title="분석 상세" onClick={()=>nav('channel',c.id)}><ChevronRight size={17}/></button></div></div>)}</div>:<Empty icon={FolderHeart} title="저장된 채널이 없습니다" desc="채널을 검색하고 분석하면 자동으로 라이브러리에 저장됩니다." button={<button className="btn btn-primary" onClick={()=>nav('search')}>채널 검색하기 <ArrowRight size={15}/></button>}/>}</div>}

function SettingsPage({onGuide,apiKey,remember,setKey,notify,refresh,busy,run,stats}:{onGuide:()=>void;apiKey:string;remember:boolean;setKey:(s:string,b:boolean)=>void;notify:(s:string)=>void;refresh:()=>Promise<void>;busy:boolean;run:(task:()=>Promise<void>)=>Promise<void>;stats:{channels:number;videos:number;owners:number}}){const [draft,setDraft]=useState(apiKey);const [saveKey,setSaveKey]=useState(remember);const [show,setShow]=useState(false);const [importMode,setImportMode]=useState<'merge'|'replace'>('merge');const [securityFlags,setSecurityFlags]=useState(readSecurityFlags);const file=useRef<HTMLInputElement>(null);
 function confirmSecurity(flag:'site'|'api',checked:boolean){const next={...securityFlags,[flag]:checked};setSecurityFlags(next);saveSecurityFlags(next);}
 async function testKey(){if(!draft.trim()){notify('API 키를 입력해 주세요.');return;}await run(async()=>{await verifyApiKey(draft.trim());setKey(draft.trim(),saveKey);notify('API 키 연결을 확인했습니다.');});}
 async function backup(){try{const data=await exportBackup();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`youtube-radar-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);notify('JSON 백업 파일을 생성했습니다.');}catch{notify('백업 생성에 실패했습니다.');}}
 async function restore(f:File){try{if(f.size>70*1024*1024)throw new Error('JSON 파일이 너무 큽니다 (70MB 이하).');const raw=JSON.parse(await f.text()) as unknown;const count=await importBackup(raw,importMode);await refresh();notify(`가져오기 완료: 채널 ${count.channels}개, 영상 ${count.videos}개 (만료 ${count.expired}개 제외)`);}catch(e){notify(e instanceof Error?`파일 검증 실패: ${e.message.slice(0,170)}`:'백업 파일이 올바르지 않습니다.');}finally{if(file.current)file.current.value='';}}
 return <div className="settings-stack"><div className="yrg-help-entry"><div><strong>API 키가 없으신가요?</strong><p>Google Cloud에서 발급하는 과정을 7단계로 자세히 안내합니다.</p></div><button type="button" onClick={onGuide}><BookOpen size={16}/> 발급 방법 보기</button></div><div className="panel"><div className="panel-head"><div><h3>개인 YouTube Data API 키</h3><p>Google Cloud에서 발급한 키를 입력합니다. 별도 서버로 전송하지 않습니다.</p></div><div className="setting-icon"><KeyRound size={19}/></div></div><div className="yrg-security-reminder"><ShieldCheck size={18}/><div><strong>연결 전 키 보호 설정을 확인하세요</strong><p>{securityFlags.site && securityFlags.api ? '가이드에서 웹사이트 제한과 API 제한을 확인하셨습니다. 실제 제한 여부는 Google Cloud에서 관리합니다.' : '발급 가이드에서 웹사이트(HTTP 리퍼러) 제한과 YouTube Data API v3 제한을 설정한 뒤 연결하는 것을 권장합니다.'}</p></div><button type="button" onClick={onGuide}>확인하기 →</button></div><div className="yrg-setting-checks"><label><input type="checkbox" checked={securityFlags.site} onChange={e=>confirmSecurity('site',e.target.checked)}/> 웹사이트(HTTP 리퍼러) 제한을 확인했어요</label><label><input type="checkbox" checked={securityFlags.api} onChange={e=>confirmSecurity('api',e.target.checked)}/> YouTube Data API v3 제한을 확인했어요</label></div><label className="field-label" htmlFor="api-key">API 키</label><div className="secret-input"><input id="api-key" type={show?'text':'password'} autoComplete="off" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="AIza..."/><button onClick={()=>setShow(!show)} aria-label={show?'API 키 숨기기':'API 키 표시'}>{show?'숨기기':'표시'}</button></div><label className="toggle-line"><input type="checkbox" checked={saveKey} onChange={e=>setSaveKey(e.target.checked)}/><span>이 브라우저에 API 키 기억하기 <small>선택하지 않으면 현재 탭을 닫을 때 키가 사라집니다.</small></span></label><div className="setting-buttons"><button className="btn btn-primary" disabled={busy||!draft.trim()} onClick={()=>void testKey()}><ShieldCheck size={17}/> 연결 확인 및 적용</button><button className="btn btn-outline" onClick={()=>{setKey('',false);setDraft('');setSaveKey(false);notify('API 키 연결을 해제했습니다.')}}>연결 해제</button></div><DataNotice>브라우저 직접 API 호출에서는 키가 네트워크 요청에 포함됩니다. Google Cloud에서 HTTP 리퍼러 및 YouTube Data API 제한을 설정하세요. 키 저장 기능은 완전한 비밀 보관 수단이 아닙니다.</DataNotice></div>
 <div className="panel"><div className="panel-head"><div><h3>로컬 저장소</h3><p>IndexedDB에 저장된 공개 채널 분석 데이터입니다.</p></div><div className="setting-icon"><HardDrive size={19}/></div></div><div className="storage-info"><div><b>{stats.channels}</b><span>채널</span></div><div><b>{stats.videos}</b><span>영상</span></div><div><b>{stats.owners}</b><span>내 기준 채널</span></div></div><DataNotice>YouTube API 콘텐츠의 저장 기한을 보수적으로 30일로 설정했습니다. 앱이 실행될 때 만료 데이터를 정리합니다. 즐겨찾기·그룹 관계는 별도로 관리됩니다.</DataNotice></div>
 <div className="panel"><div className="panel-head"><div><h3>JSON 데이터 백업 및 복원</h3><p>다른 브라우저로 데이터를 옮기거나 직접 백업할 수 있습니다.</p></div><div className="setting-icon"><FileJson size={19}/></div></div><div className="backup-grid"><div className="backup-box"><Download size={23}/><b>데이터 내보내기</b><p>유효한 채널·영상·그룹 데이터를 JSON 파일로 저장합니다. API 키는 제외합니다.</p><button className="btn btn-primary" onClick={()=>void backup()}><Download size={16}/> JSON 다운로드</button></div><div className="backup-box"><Upload size={23}/><b>데이터 가져오기</b><p>이 앱에서 내보낸 JSON을 복원합니다. 만료된 통계는 가져오지 않습니다.</p><Select value={importMode} onChange={v=>setImportMode(v as 'merge'|'replace')} ariaLabel="백업 복원 방식"><option value="merge">기존 데이터와 병합</option><option value="replace">기존 데이터 교체</option></Select><button className="btn btn-outline" onClick={()=>file.current?.click()}><Upload size={16}/> JSON 파일 선택</button><input ref={file} type="file" accept="application/json,.json" hidden onChange={e=>{const f=e.target.files?.[0];if(f){if(importMode==='replace'&&!confirm('기존 저장 데이터를 JSON 내용으로 교체하시겠습니까?'))return;void restore(f);}}}/></div></div></div>
 <div className="panel danger-zone"><div className="panel-head"><div><h3>전체 분석 데이터 삭제</h3><p>현재 브라우저에 저장된 채널·영상·그룹·통계 기록을 삭제합니다. 취소할 수 없습니다.</p></div></div><button className="btn btn-danger" onClick={()=>{if(confirm('정말 모든 로컬 분석 데이터를 삭제하시겠습니까? JSON 백업으로만 복구할 수 있습니다.'))void resetAll().then(refresh).then(()=>notify('로컬 분석 데이터가 삭제됐습니다.'));}}><Trash2 size={16}/> 모든 데이터 삭제</button></div>
 <div className="setting-footnotes"><a href="https://console.cloud.google.com/apis/library/youtube.googleapis.com" target="_blank" rel="noreferrer"><ExternalLink size={14}/> Google Cloud YouTube Data API 설정</a><a href="https://developers.google.com/youtube/terms/developer-policies" target="_blank" rel="noreferrer"><ExternalLink size={14}/> YouTube API 개발자 정책</a></div></div>}
